### ISSUE TITLE
Imgur gallery doesn't work

### ISSUE THREAD

**Issue by Smile4ever** [rharel/webext-new-tab-tweaker#2]
I've tried to use http://imgur.com/gallery/hOF1g as imgur album, but it doesn't work. Probably because this is not a "real" album?

**Comment by rharel** [comment]
Yes, we currently use only the album API, which is different from the one for galleries. I'll look into this.

**Comment by rharel** [comment]
Fixed in 6de270ace9e6858a23cd981fc98e65e0772f1cd3
