### ISSUE TITLE
Support for local files

### ISSUE THREAD

**Issue by Smile4ever** [rharel/webext-new-tab-tweaker#3]
I've tried to write "file:///data/wallpaper-2119535.jpg" but that doesn't work.

**Comment by rharel** [comment]
This is a limit of the WebExtension API, as Firefox does not allow for scripted access to the filesystem citing security concerns. A workaround is to either host the images on a local server (but that's a bit overkill) or to upload them somewhere (e.g. Imgur) and link from there.

**Comment by Smile4ever** [comment]
On Linux, I use http://www.rejetto.com/hfs/ under Wine. HFS is a HTTP File Server, so it maps
/data/wallpaper.jpg to http://192.168.1.30:8080/data/wallpaper.jpg. That way I can use local files inside New Tab Tweaker. I've configured HFS to start when I start my computer.

HFS should also work on Windows, and might also work on macOS when using Wine.

**Comment by Smile4ever** [comment]
I've found this bug report which is at P2 priority: 
Implement local filesystem read/write access.
https://bugzilla.mozilla.org/show_bug.cgi?id=1246236

**Comment by yfdyh000** [comment]
[Bug 1266960](https://bugzilla.mozilla.org/show_bug.cgi?id=1266960) - Extensions can not load file: URLs
is true bug.
