### ISSUE TITLE
Add multiple scaling methods for background image

### ISSUE THREAD

**Issue by Smile4ever** [rharel/webext-new-tab-tweaker#4]
It would be useful to be able to choose between scaling methods:
* Zoomed
* Scaled
* Stretched
...

**Comment by rharel** [comment]
Good suggestion, I'll try to get this into the next release.

**Comment by Smile4ever** [comment]
"Centered" is another option you might want to consider. Looking forward to your reaction on my pull requests :-)

**Comment by rharel** [comment]
Thanks for contributing! I have other obligations to tend to in the next few days, but I expect to get to review your pull-requests in about a week.

**Comment by Smile4ever** [comment]
You're welcome. I will be patiently waiting.

**Comment by rharel** [comment]
This issue has been split into #11, #12, #13
