### ISSUE TITLE
Support for (HTTP) image folders

### ISSUE THREAD

**Issue by Smile4ever** [rharel/webext-new-tab-tweaker#7]
Suppose I have the http://localhost/images/ folder which contains 20 wallpapers:
* wallpaper-sea.jpg
* wallpaper-beach.jpg
* ...

I would like to be able to add all those files by specifying "http://localhost/images/" as an image source. That way I can dynamically add new wallpapers to a folder without changing the options of New Tab Tweaker every single day.

**Comment by rharel** [comment]
This is definitely doable, and I have begun working on it.

**Comment by rharel** [comment]
[Version 1.6.0b4](https://addons.mozilla.org/en-US/firefox/addon/new-tab-tweaker/versions/1.6.0b4) now supports this. The idea is that if a URL ~~is not linking to an image directly (i.e. does not have an image extension or does not begin with 'data:')~~ __is prefixed by `[list]`__ then it is expected for it to return a plaintext response with a list of direct image URLs separated by newlines.

So to get this to work with [HFS](http://www.rejetto.com/hfs/), if your image folder is at `localhost/wallpapers` then simply supply the following: `http://localhost/wallpapers/?tpl=list`

Edit: To include subfolders in the listing, use `http://localhost/wallpapers/?tpl=list&folders-filter=\&recursive`

**Comment by Smile4ever** [comment]
I'm sorry but this doesn't work for me at all:
* Subfolders are not taken into account
* I don't get any images, even when I specify a folder like this: http://localhost/wallpapers/?tpl=list

**Comment by rharel** [comment]
I think that if you want to include subfolders in the listing you should add `&folders-filter=\&recursive` to the URL.

**Comment by rharel** [comment]
As for why you don't get to see images at all, I'm not sure what's the cause (it works fine here). Does the console display any errors?

**Comment by Smile4ever** [comment]
I investigated and I figured it out.

* Probably the checkbox "Display a wallpaper image" was turned off.
* I had fading set to 1.5 seconds

The implementation also seems very slow. It takes 1.5 seconds from the moment I open a new tab to the state where an image from localhost is loaded when using folders. This is at least half the fault of HFS:

$ curl -w "@curl-format.txt" -o /dev/null -s "http://localhost:8080/wallpapers/?tpl=list&folders-filter=\&recursive"
    time_namelookup:  0,004217
       time_connect:  0,006600
    time_appconnect:  0,000000
   time_pretransfer:  0,006626
      time_redirect:  0,000000
 time_starttransfer:  0,886853
                    ----------
         time_total:  0,887922

Can you cache these "list folder contents" requests?

**Comment by rharel** [comment]
Isn't it easier to configure HFS to set the cache headers and let firefox do the rest, rather than caching on our side?

The delay is quite curious, I am using Windows and image loading is instantaneous.

**Comment by Smile4ever** [comment]
> Isn't it easier to configure HFS to set the cache headers and let firefox do the rest, rather than caching on our side?

I wish it was, but I can't seem to find the option to set Cache-Control in HFS.

> The delay is quite curious, I am using Windows and image loading is instantaneous.

Image folder with how many images? I have a folder (and subfolders) with in total of 574 items in it.

**Comment by rharel** [comment]
It seems one way to do it is (assuming advanced mode): Menu -> Other options -> Edit event scripts
Then insert:
```
[request]
{.add header | <your header of choice> .}
```

**Comment by Smile4ever** [comment]
I tried 

> [request]
> {.add header|Cache-Control: Public.}

but that doesn't work. I opened a topic asking how to achieve this:
http://www.rejetto.com/forum/hfs-~-http-file-server/controlling-the-cache-control-header/

**Comment by Smile4ever** [comment]
I'm writing my own solution instead of using HFS. Could you ignore everything after ; please (or use indexOf instead of exact match)?

Console error from controller.js
"Expected text/plain response from http://localhost:8000/,got text/plain; charset=utf-8 instead."

**Comment by rharel** [comment]
Done in [1.6.0b5](https://addons.mozilla.org/en-US/firefox/addon/new-tab-tweaker/versions/1.6.0b5)
